<?php

/**
 * @file
 * Primary module hooks for Specbee Location module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
 * Implements hook_theme().
 */
function specbee_location_theme() {
    return [
      'location_block' => [
        'variables' => [
          'content' => NULL
        ],
        'render element' => 'children',
      ],
      'location' => [
        'variables' => [
          'content' => NULL
        ],
        'render element' => 'children',
      ]
    ];
  }
